### PR TITLE
Serokell test

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by gromakovsky** [comment]
@hasufell hey, could you please upload this new version to Hackage?

**Comment by hasufell** [comment]
@gromakovsky sure, but no application code was changed. This is just metadata stuff, so I guess I could just update stack2cabal.cabal on hackage?

**Comment by gromakovsky** [comment]
Yes, I think that should work, though I never tried to do it myself :slightly_smiling_face: 

Btw, a newer version of `hpack` is now available (0.34.4), it'd be great to support it as well :wink:

**Comment by hasufell** [comment]
See https://hackage.haskell.org/package/stack2cabal-1.0.12/revisions/

It's available as the same version after a `cabal update`.

**Pull request merged**
